### ISSUE TITLE
Review implementation of arduino LED

### ISSUE THREAD

**Issue by arlevin** [Nashoba-Robotics/Nashoba-Robotics2017#13]
The arduino led system is an important part of the Driver station, but it was implemented quickly both in HW and SW during last year's build season.  It is worth taking some time to see if this implementation can be simplified so it is easier to maintain and improve as needed.

**Comment by Ipsum** [comment]
From what I understand, it was just hard to physically maintain such as when an LED burned out? Any problems interfacing with the robot/laptop?

**Comment by arlevin** [comment]
Could be; I honestly don't remember if there were SW issues or only HW issues or perhaps HW issues that arose because of our SW implementation.  In any case, while reviewing the implementation, I'd like to fully train one or more of the other control team members on maintaining the arduino so it is completely out of Garrison's hands.  This was probably unclear from my poor description.

**Comment by gbear605** [comment]
I don't believe that there was any issues with maintaining it once it was
complete. The only issues with burnt out LEDs was the few that were already
burnt out when we installed it. For those, we did decide to just leave them
in instead of replacing them because of the high difficulty of modifying
the system, given the time constraints and priorities.
